#242: Use eslint to improve code readability.
Contains just the configuration for eslint. Code changes will be made in a later commit.

Similar changes were made to obsidian-sample-plugin: https://github.com/obsidianmd/obsidian-sample-plugin/commit/6fdd374cb8e46505dcef70ff249b48b16c4a659b
Exception: I needed to add "eslint": "8.20.0" myself to package.json.